linters:
  disable-all: true
  enable:
    - gofmt
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - stylecheck

run:
  skip-files:
    # These were code-generated, and cannot be changed without breaking RPC compatibility.
    - lambda/messages/*.go

linters-settings:
  stylecheck:
    go: "1.20"
    checks:
      - "all"
    initialisms:
      - "ACL"
      - "AMQP"
      - "API"
      - "ARN"
      - "ASCII"
      - "AWS"
      - "CPU"
      - "CSS"
      - "DB"
      - "DNS"
      - "EOF"
      - "GID"
      - "GUID"
      - "HTML"
      - "HTTP"
      - "HTTPS"
      - "IAM"
      - "ID"
      - "IP"
      - "JSON"
      - "MQTT"
      - "QPS"
      - "RAM"
      - "RPC"
      - "RTP"
      - "SIP"
      - "SLA"
      - "SMTP"
      - "SQL"
      - "SSH"
      - "TCP"
      - "TLS"
      - "TS"
      - "TTL"
      - "UDP"
      - "UI"
      - "UID"
      - "URI"
      - "URL"
      - "UTF8"
      - "UUID"
      - "VM"
      - "VPC"
      - "XML"
      - "XMPP"
      - "XSRF"
      - "XSS"
